# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

APPSTORE_CONNECT_APP_ID = ENV["APPSTORE_CONNECT_APP_ID"]
BUNDLE_IDENTIFIER = ENV["BUNDLE_IDENTIFIER"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
API_KEY_ISSUER_ID = ENV["API_KEY_ISSUER_ID"]
API_KEY_ID = ENV["API_KEY_ID"]
API_KEY = ENV["API_KEY"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]


def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  lane :closed_beta do
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD

    api_key = app_store_connect_api_key(
      key_id: API_KEY_ID,
      issuer_id: API_KEY_ISSUER_ID,
      key_content: API_KEY,            
      duration: 1200,            
      in_house: false
    )
    
    increment_build_number(xcodeproj: "Owl.xcodeproj")

    
  end
end