name: DeployStaging
on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions a tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Firebase App Distribution
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.3.1'

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Install bundle
        run: bundle install

      - name: GIT setup config
        run: |
          git config --global user.name "CI"
          git config --global user.email "owl.tech.company@gmail.com"

      - name: Deploy iOS Staging to Firebase App Distribution via Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: deploy_staging
        env:
          FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 10
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 100
          APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
          APPLE_ID: '${{ secrets.APPLE_ID }}'
          DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
          TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
          TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
          BUNDLE_IDENTIFIER_STAGING: '${{ secrets.BUNDLE_IDENTIFIER_STAGING }}'
          FIREBASE_APP_ID: '${{ secrets.FIREBASE_APP_ID }}'
          FIREBASE_CLI_TOKEN: '${{ secrets.FIREBASE_CLI_TOKEN }}'
